### PR TITLE
Initialised Basic Flutter App

### PR DESCRIPTION
**Pull request by sehejjain**
Initialized default Flutter App and added folders to start working.

### CODE REVIEW

**Comment by garg3133** [comment]
Are you sure you need to have all these files on GitHub? I think you've also pushed the environment files in it.

**Comment by sehejjain** [comment]
Actually yes. In flutter, there isn't an environment per see.
Both the Pubspec Files are to manage are required for package management.
All the other folders except .idea and .dart_tool are required for building the app.

The .idea folder is generated by the IDE. I would not have added it to the commit but As of 2020, JetBrains suggests to commit the .idea folder.

The .dart_tool is required for the IDE tools that make using flutter a lot easier.

**Comment by sehejjain** [comment]
If you are talking about any other files, then do tell me, I'll look into it.

**Comment by garg3133** [comment]
Oh.. okay then! Merging this PR into `main`.

**Pull request merged**
